dataset:
  name: olist_brazilian_ecommerce
  source_platform: Kaggle
  kaggle_dataset: olistbr/brazilian-ecommerce
  source_method_default: manual_download

expected_files:
  - olist_orders_dataset.csv
  - olist_order_items_dataset.csv
  - olist_customers_dataset.csv
  - olist_sellers_dataset.csv
  - olist_products_dataset.csv
  - olist_order_payments_dataset.csv
  - olist_order_reviews_dataset.csv
  - olist_geolocation_dataset.csv
  - product_category_name_translation.csv
