olist_orders_dataset.csv:
  - order_id
  - customer_id
  - order_status
  - order_purchase_timestamp
  - order_delivered_customer_date
  - order_estimated_delivery_date

olist_order_items_dataset.csv:
  - order_id
  - order_item_id
  - product_id
  - seller_id
  - price
  - freight_value

olist_customers_dataset.csv:
  - customer_id
  - customer_zip_code_prefix
  - customer_city
  - customer_state

olist_sellers_dataset.csv:
  - seller_id
  - seller_zip_code_prefix
  - seller_city
  - seller_state

olist_products_dataset.csv:
  - product_id
  - product_category_name

olist_order_payments_dataset.csv:
  - order_id
  - payment_value
  - payment_type

olist_order_reviews_dataset.csv:
  - review_id
  - order_id
  - review_score

olist_geolocation_dataset.csv:
  - geolocation_zip_code_prefix
  - geolocation_lat
  - geolocation_lng
  - geolocation_city
  - geolocation_state

product_category_name_translation.csv:
  - product_category_name
  - product_category_name_english
